version: '3'

services:
    deployer:
        build: .
        ports:
            - '12045:5000'
        volumes:
            - ./token:/srv/token
            - ./deployment:/srv/deployment
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DOCKER_COMPOSE_SERVICES=hello-world
